name: ieect_books
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  pdfx: ^2.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/pdf/level2/M01.pdf
    - assets/pdf/level2/M02.pdf
    - assets/pdf/level2/M03.pdf
    - assets/pdf/level2/M03.pdf
    - assets/pdf/level2/M04.pdf
    - assets/pdf/level2/M05.pdf
    - assets/pdf/level2/M06.pdf
    - assets/pdf/level2/M07.pdf
    - assets/pdf/level2/M08.pdf
    - assets/pdf/level2/M09.pdf
    - assets/pdf/level2/M10.pdf
    - assets/pdf/level2/M11.pdf
    - assets/image/Learning-bro.png

    
    
